### ISSUE TITLE
todo: update and codument build-install process

### ISSUE THREAD

**Issue by mckaygerhard** [MoonLightDE/mlde.l.liblxqt#5]
- [ ] update README's of the repository
- [ ] create references to docs/README 
- [ ] document the build process
- [ ] document the install process
- [ ] create a issue to mark ducment develop, usage of cmake and pkgconfig
- [ ] publish and update task in MoonLightDE/mlde.d.moonlightde#47
